name: Docker Compose Actions Workflow
on:
  push:
    branches: 
      - wagtail

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # - name: Build and Test
      #   run: docker-compose -f docker-compose.ci.yml up -d

      # - name: Check running containers
      #   run: docker ps -a

      # - name: Check logs
      #   run: docker logs mrd_django

      # - name: Django Tests
      #   run: docker-compose exec -T mrd_django pytest


      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: madden1706/madresearchden/website:latest